### ISSUE TITLE
About the data

### ISSUE THREAD

**Issue by Nyquixt** [BrianG13/FLEX#4]
Upon inspecting the data, I notice that the 3D data, i.e. 3D pose and 3D rotation, also have the view element to them. In the evaluation code, the prediction of the network also contains the view dimension for 3D data. Why is this the case? They should be uniform across all views and should not have the view dimension, both intuitively and as stated in the paper. Am I missing something here?

**Comment by BrianG13** [comment]
I will refer to 3D pose and 3D rotations separately.

3D rotations are the same across all the views, except the pelvis/global rotation.
Why? The person rotations are the same no matter which camera are you looking from, and the only thing that differs the different camera is the orientation of the person relatively to each camera.

3D pose is different for each camera.
Why? Because the 3D Pose is relative to the camera axis. Our algorithm output is joint rotations, to get 3D pose we apply Forward-Kinematics (using predicted bones lengths and joint rotations). For each view we have a different global orientation (the rest of the rotations are the same for all views), so for each view different 3D pose.

I hope you find this helpful :)

**Comment by Nyquixt** [comment]
Oh that makes sense. I disregard the relativity to camera for some reasons. Thanks for the explanation.
